### ISSUE TITLE
supporting OSX backend

### ISSUE THREAD

**Issue by smondet** [ocaml/ocaml-travisci-skeleton#15]
A few projects got the right to experiment with new `osx` boxes on Travis.

Right now this requires working around: https://github.com/ocaml/opam/issues/1853
(`brew install opam --HEAD` seems to do it for now).

See these scripts using the OSX backend:

- https://github.com/hammerlab/ketrew/blob/use_trakeva/tools/travis_ci_test.sh
- https://github.com/samoht/assemblage/blob/master/.travis-ci.sh

**Comment by samoht** [comment]
That's a very good idea, and patches are welcome :-)
