### ISSUE TITLE
DEPOPTS variable confusion

### ISSUE THREAD

**Issue by agarwal** [ocaml/ocaml-travisci-skeleton#20]
DEPOPTS is being used for 2 different purposes:
* as a true/false variable to determine if a run with the optional dependencies should be done
* the names of the optional packages

If you set DEPOPTS=true, you end up also having "true" as the name of the optional package to install.

The README should also be fixed. Right now it mentions the second usage above for DEPOPTS.

**Comment by samoht** [comment]
Patches on the README are very welcome!
