### ISSUE TITLE
document reverse dependency feature

### ISSUE THREAD

**Issue by avsm** [ocaml/ocaml-travisci-skeleton#27]
REVDEPS is not mentioned in the README

**Comment by dsheets** [comment]
It would be nice if one could filter the REVDEPS rather than testing all of them. Some of them may be unmaintained/broken or central packages could have lots. Often, maintainers know which reverse packages themselves have few dependencies and make heavy use of their API.

**Comment by samoht** [comment]
could use the `POST_INSTALL_HOOKS` for this I guess.

**Comment by samoht** [comment]
At one point, would be better to rewrite everything in ocaml ... :p
