### ISSUE TITLE
.travis-opam.sh doesn't run tests as part of depopts build

### ISSUE THREAD

**Issue by johnelse** [ocaml/ocaml-travisci-skeleton#30]
At the moment `depopts_run` and `tests_run` are handled orthogonally; there's no way to test e.g. a package which is only built if Lwt is installed.

**Comment by edwintorok** [comment]
Looks like this got reverted in: https://github.com/ocaml/ocaml-ci-scripts/commit/cbd03c25d5c275f5b7aa4b3d6019c1906ca1c3b7
